# Generated by Django 3.1.7 on 2021-03-14 10:24

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('date_published', models.DateTimeField()),
                ('body_text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=blog.models.image_upload)),
            ],
        ),
    ]
